//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementDetail
    {
        public int DisbursementDetailsID { get; set; }
        public int DisbursementID { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> CollectedQty { get; set; }
        public string Reason { get; set; }
        public int RequisitionDetailsID { get; set; }
    
        public virtual Disbursement Disbursement { get; set; }
        public virtual RequisitionDetail RequisitionDetail { get; set; }
    }
}
