//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementDuty
    {
        public int DisbursementDutyID { get; set; }
        public string StoreClerkID { get; set; }
        public bool isRetreived { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
