//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disbursement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disbursement()
        {
            this.DisbursementDetails = new HashSet<DisbursementDetail>();
        }
    
        public int DisbursementID { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public int RequisitionID { get; set; }
        public Nullable<int> CollectedBy { get; set; }
        public int DisbursementDutyID { get; set; }
    
        public virtual DepartmentRepresentative DepartmentRepresentative { get; set; }
        public virtual DisbursementDuty DisbursementDuty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisbursementDetail> DisbursementDetails { get; set; }
        public virtual Requisition Requisition { get; set; }
    }
}
