//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StationeryStoreEntities : DbContext
    {
        public StationeryStoreEntities()
            : base("name=StationeryStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApprovalStatus> ApprovalStatus1 { get; set; }
        public virtual DbSet<Authority> Authorities { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CollectionPoint> CollectionPoints { get; set; }
        public virtual DbSet<DeliveryStatus> DeliveryStatus1 { get; set; }
        public virtual DbSet<DepartmentRepresentative> DepartmentRepresentatives { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Disbursement> Disbursements { get; set; }
        public virtual DbSet<DisbursementDetail> DisbursementDetails { get; set; }
        public virtual DbSet<DisbursementDuty> DisbursementDuties { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<InvoiceUploadStatus> InvoiceUploadStatus1 { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderSupplierDetail> OrderSupplierDetails { get; set; }
        public virtual DbSet<OrderSupplier> OrderSuppliers { get; set; }
        public virtual DbSet<Requisition> Requisitions { get; set; }
        public virtual DbSet<RequisitionDetail> RequisitionDetails { get; set; }
        public virtual DbSet<RetrievalStatus> RetrievalStatus { get; set; }
        public virtual DbSet<StockTransaction> StockTransactions { get; set; }
        public virtual DbSet<StockVoucher> StockVouchers { get; set; }
        public virtual DbSet<SupplierItem> SupplierItems { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<StockCountItem> StockCountItems { get; set; }
        public virtual DbSet<OutstandingRequisitionView> OutstandingRequisitionViews { get; set; }
        public virtual DbSet<ReorderDetail> ReorderDetails { get; set; }
        public virtual DbSet<RetreivalItem> RetreivalItems { get; set; }
    }
}
