//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutstandingRequisitionView
    {
        public int RequisitionDetailsID { get; set; }
        public Nullable<int> OutStandingQuantity { get; set; }
        public string itemID { get; set; }
        public string DepartmentID { get; set; }
        public System.DateTime ApproveDate { get; set; }
    }
}
