//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutstandingRequisitionView
    {
        public Nullable<int> RequisitionID { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public int RequisitionDetailsID { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> OutStandingQuantity { get; set; }
    
        public virtual RequisitionDetail RequisitionDetail { get; set; }
    }
}
