//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockVoucher
    {
        public int DiscrepancyID { get; set; }
        public string ItemID { get; set; }
        public int OriginalCount { get; set; }
        public int ActualCount { get; set; }
        public decimal ItemCost { get; set; }
        public string Reason { get; set; }
        public string RaisedBy { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> RaisedByDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    
        public virtual Employee ApprovedByEmployee { get; set; }
        public virtual Employee RaisedByEmployee { get; set; }
        public virtual Item Item { get; set; }
    }
}
