//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransaction
    {
        public int TransactionID { get; set; }
        public string ItemID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Adjustment { get; set; }
        public string EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Item Item { get; set; }
    }
}
